# Generated by Django 6.0.2 on 2026-03-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
