# Generated by Django 6.0.2 on 2026-03-06 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage_is_deleted'),
        ('student_management', '0013_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Dushanba'), (2, 'Seshanba'), (3, 'Chorshanba'), (4, 'Payshanba'), (5, 'Juma'), (6, 'Shanba'), (7, 'Yakshanba')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='student_management.group')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('room', 'day_of_week', 'start_time')},
            },
        ),
    ]
