# Generated by Django 6.0.2 on 2026-03-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_timetable_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
    ]
