# Generated by Django 6.0.2 on 2026-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
