# Generated by Django 6.0.2 on 2026-03-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_seen',
        ),
    ]
