# Generated by Django 6.0.2 on 2026-03-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
