# Generated by Django 6.0.2 on 2026-02-12 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Gender')),
                ('current_academic_level', models.CharField(choices=[('P.1', 'Primary 1'), ('P.2', 'Primary 2'), ('P.3', 'Primary 3'), ('P.4', 'Primary 4'), ('P.5', 'Primary 5')], max_length=10, verbose_name='Current Academic Level')),
                ('enrollment_status', models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], max_length=20, verbose_name='Enrollment Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
