# Generated by Django 6.0.2 on 2026-02-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('score', models.PositiveIntegerField(verbose_name='Bahosi')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_management.student')),
            ],
        ),
    ]
