# Generated by Django 6.0.2 on 2026-03-05 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0011_alter_news_options_news_likes_news_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video sarlavhasi')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='YouTube havola')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video yangilik',
                'verbose_name_plural': 'Video yangiliklar',
            },
        ),
    ]
