# Generated by Django 6.0.2 on 2026-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0014_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
