# Generated by Django 6.0.2 on 2026-03-12 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0015_news_dislikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
