# Generated by Django 6.0.2 on 2026-02-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_subject_remove_grade_comment_alter_grade_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.subject'),
        ),
    ]
