# Generated by Django 6.0.2 on 2026-03-03 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_attendance_updated_at_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-created_at'], 'verbose_name': 'Talaba', 'verbose_name_plural': 'Talabalar'},
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.CharField(choices=[('active', 'Active'), ('dismissed', 'Dismissed'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], default='active', max_length=20, verbose_name='Enrollment Status'),
        ),
    ]
