# Generated by Django 6.0.2 on 2026-03-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0017_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('playlist_id', models.CharField(help_text='Pleylist ID sini kiriting (masalan: PL...)', max_length=100)),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rsatish")),
            ],
        ),
    ]
